Include `Which` for `HomebrewUserWrapper`
sous-chefs/homebrew pull request #184
Opened 2024-05-06 18:00 UTC by jazaval

# Description

Explicitly include `Which` module from `Chef` which fixes cookbook use on newer 18.x clients. 

## Issues Resolved

Fixes #183 

## Check List

- [✅] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [❌] New functionality includes testing.
- [❌] New functionality has been documented in the README if applicable.

2024-05-06 18:42 UTC, Stromweld requested changes

2024-05-06 18:42 UTC, Stromweld commented on CHANGELOG.md
> +## 5.4.6 - *2024-05-06*
don't include the version bump, sous-chefs automation takes care of that. Just need the ##Unreleased header and description of changes under it.

2024-05-06 18:42 UTC, Stromweld commented on metadata.rb
> +version          '5.4.6'
sous-chefs automation will handle version bumping the CB version here.

2024-05-06 18:49 UTC, Stromweld commented
Users should be using the built in homebrew resources for chef-client > 14. Not sure what this fix is needed for?

2024-05-07 00:43 UTC, jazaval commented
Chef client won't install homebrew itself, which is generally the core remaining use here (default recipe).

2024-05-07 20:25 UTC, Stromweld approved these changes
LGTM

2024-05-07 20:26 UTC, merged

2024-05-07 20:27 UTC, kitchen-porter commented
Released as: [5.4.8](https://github.com/sous-chefs/homebrew/releases/tag/5.4.8)